apiVersion: v2
name: postgresql
description: A Helm chart for PostgreSQL
type: application
version: 1.0.0
dependencies:
  - name: postgresql
    version: 15.5.23
    repository: https://charts.bitnami.com/bitnami

